version: "3.8"
services:
  database:
    image: mysql:5.7.37
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
      MYSQL_ROOT_PASSWORD: testpassword
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysqldata:/var/lib/mysql
      - "./database:/docker-entrypoint-initdb.d"
volumes:
  mysqldata:
    driver: local